amd-zynqmp: README: add xsct package to CUSTOMER_RECIPES
Issue: LIN1024-3330

The commit 3d82c7e ("xsct-native: Move from class to recipe install") in
meta-xilinx-tools layer add "xsct-native" to the "DEPENDS" variable, so
update README to fix the build error:

    ERROR: Nothing PROVIDES 'xsct-native' (but layers/meta-xilinx-tools/recipes-bsp/bitstream/bitstream-extraction_git.bb, layers/meta-xilinx/meta-xilinx-core/recipes-bsp/device-tree/device-tree.bb DEPENDS on or otherwise requires it)
    xsct-native was skipped: Not supported in this configuration by Wind River. To override, add to your local.conf:
    CUSTOMER_RECIPES:xilinx-tools += 'xsct' xsct-native was skipped: We can't extend native recipes

    You may also have to add: BB_NO_NETWORK = '0'
    ERROR: Required build target 'xilinx-bootbin' has no buildable providers.
    Missing or unbuildable dependency chain was: ['xilinx-bootbin', 'virtual/bitstream', 'xsct-native']

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>